# Generated by Django 5.2.17 on 2026-08-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("usage_date", models.DateField()),
                ("used_tokens", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_token_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-usage_date"], name="accounts_da_user_id_4df5b6_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "usage_date"), name="accounts_unique_daily_token_usage"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("used_tokens__gte", 0)),
                        name="accounts_daily_usage_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                ("daily_token_limit", models.PositiveIntegerField(default=20000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("daily_token_limit__gt", 0)),
                        name="accounts_subscription_positive_daily_limit",
                    )
                ],
            },
        ),
    ]
